frontend:

input_boolean:
  test_heater:
    name: Test heater
  test_heater_office:
    name: Test office heater
  test_heater_lounge:
    name: Test lounge heater

input_number:
  test_temperature:
    name: Test temperature
    min: 10
    max: 40
    step: 0.5
    initial: 22
  test_temperature_office:
    name: Test office temperature
    min: 10
    max: 40
    step: 0.5
    initial: 22
  test_temperature_lounge:
    name: Test lounge temperature
    min: 10
    max: 40
    step: 0.5
    initial: 22

climate:
  - platform: generic_thermostat
    name: Test Climate
    heater: input_boolean.test_heater
    target_sensor: input_number.test_temperature
    ac_mode: true
    initial_hvac_mode: cool
    min_temp: 60.8
    max_temp: 86
  - platform: generic_thermostat
    name: Test Climate Office
    heater: input_boolean.test_heater_office
    target_sensor: input_number.test_temperature_office
    ac_mode: true
    initial_hvac_mode: cool
    min_temp: 60.8
    max_temp: 86
  - platform: generic_thermostat
    name: Test Climate Lounge
    heater: input_boolean.test_heater_lounge
    target_sensor: input_number.test_temperature_lounge
    ac_mode: true
    initial_hvac_mode: cool
    min_temp: 60.8
    max_temp: 86

http:
  server_host: 127.0.0.1
  server_port: 8124

logger:
  default: info
  logs:
    custom_components.climate_flow: debug
    homeassistant.components.config: debug
    homeassistant.config_entries: debug
    homeassistant.loader: debug
    homeassistant.setup: debug
